spring.application.name=module1
server.port = 9090
notification.type = email
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:/Users/apple/Documents/springboottutorial/db
spring.datasource.username = omkar
spring.datasource.password = pass
spring.jpa.hibernate.ddl-auto=update